services:
  db:
    image: mariadb:10.11.2
    volumes:
      - db_data_prestashop:/var/lib/mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop_user
      MYSQL_PASSWORD: 123456789
    networks:
      - prestashop_network

  prestashop:
    depends_on:
      - db
    image: prestashop/prestashop:latest
    ports:
      - "9800:80"
    restart: no
    environment:
      PS_DEV_MODE: 0
      PS_HOST_MODE: 0
      PS_DEMO_MODE: 0
      DB_SERVER: db
      DB_USER: prestashop_user
      DB_PASSWD: 123456789
      DB_PREFIX: ps_
      DB_NAME: prestashop
      PS_LANGUAGE: en
      PS_SHOP_NAME: tarea_SXE
      PS_DOMAIN: "localhost:9800"
    networks:
      - prestashop_network

volumes:
  db_data_prestashop:

networks:
  prestashop_network:

